services:
  rp:
    build:
      context: .
      dockerfile: docker/Dockerfile_rp
      args:
        UID: ${UID}
        GID: ${GID}
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - type: bind
        source: ./rp/nginx.conf.dev
        target: /etc/nginx/nginx.conf
      - ./rp/conf.d/:/etc/nginx/conf.d/
      - ./rp/certs/:/etc/nginx/certs/
    env_file:
      - ./.env
    # command: >
    #   /bin/sh -c 
    #   "envsubst '
    #   $$WP_FQDN
    #   $$GATS_FQDN
    #   $$WP_HOST_PORT
    #   $$HOST_IP
    #   ' < /etc/nginx/conf.d/dev.conf.template > /etc/nginx/conf.d/dev.conf
    #   && nginx -g 'daemon off;'"
    networks:
      - internal

networks:
  internal:
    driver: bridge